version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "18:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gulp-replace
    versions:
    - 1.1.0
    - 1.1.1
  - dependency-name: jsdom
    versions:
    - 16.5.0
    - 16.5.1
    - 16.5.2
  - dependency-name: simple-git
    versions:
    - 2.36.1
    - 2.36.2
    - 2.37.0
  - dependency-name: clipboard
    versions:
    - 2.0.7
  - dependency-name: mocha
    versions:
    - 8.3.1
  - dependency-name: chai
    versions:
    - 4.3.3
  - dependency-name: htmlparser2
    versions:
    - 6.0.1
